### ISSUE TITLE
 Assertion `dummy == "S"' failed.

### ISSUE THREAD

**Issue by gsc74** [algbio/GraphChainer#2]
_gchandra@loginsiddhi:~/GraphChainer/Human$_**/nlsasfs/home/dnarna/gchandra/GraphChainer/GraphChainer/bin/GraphChainer -t 128 -f /nlsasfs/home/dnarna/gchandra/BWA/Data/ERR194147_1.fastq.gz -f /nlsasfs/home/dnarna/gchandra/BWA/Data/ERR194147_2.fastq.gz -g /nlsasfs/home/dnarna/gchandra/GraphChainer/Human/Graph/graph.gfa -a out.gam**

GraphChainer Branch master commit 403cff6d1f4a385126a25199f00f68e24f28db7f 2022-01-05 10:59:13 +0200
GraphChainer Branch master commit 403cff6d1f4a385126a25199f00f68e24f28db7f 2022-01-05 10:59:13 +0200
Co-linear chaining on splits=(35,35,10000)
Load graph from /nlsasfs/home/dnarna/gchandra/GraphChainer/Human/Graph/graph.gfa
GraphChainer: src/GfaGraph.cpp:231: static GfaGraph GfaGraph::LoadFromStream(std::istream&, bool, bool): Assertion `dummy == "S"' failed.
Aborted (core dumped)

Constructed Graph with;
**vg construct -t 128 -a -r Homo_sapiens_assembly38.fasta -v Homo_sapiens_assembly38.known_indels.vcf.gz  -p -m 3000000 > graph.gfa**

**Comment by abanerjee10** [comment]
How was this resolved? I have a similar issue with alignment to a gfa graph giving an assertion error from the same method:

GfaGraph::LoadFromStream(std::istream&, bool, bool): Assertion `dummyc == 'M' || (dummyc == 'S' && overlap == 0)' failed.

Command:
GraphChainer -t 24 --graph=brca1.gfa --reads=brca1.fastq --alignments-out=brca1.gam
Graph:
https://github.com/ParBLiSS/PaSGAL/blob/master/data/BRCA1.vg
vg view BRCA1.vg >brca1.gaf

**Comment by elarielcl** [comment]
Hi @abanerjee10 thanks for your question.
This is method loads the gfa graph from file.

In the case of @gsc74  the assertion checks if a node line from the gfa file starts with "S ", so I suppose the graph he was using was starting with "Sx" (as for getting to the assertion the line needs to start with "S"). @gsc74 closed the issue back in the day, so this person probably knows better :)

In your case the assertion comes when parsing an edge line in the gfa file.

Thanks for providing the input for your issue, this is very helpful!
I tried to reproduce your problem but I couldnt get the error, I used [https://github.com/vgteam/vg/releases/tag/v1.46.0](https://github.com/vgteam/vg/releases/tag/v1.46.0) to convert the vg file to gfa and got the following [graph](https://me.ariel.computer/files/BRCA1.gfa), which does not give me the assertion error.
I wonder if this is related to the vg version. I also noted that in the last command you wrote `vg view BRCA1.vg >brca1.gaf` (instead of gfa, so maybe there was a small mistake related to that)

**Comment by gsc74** [comment]
> Hi @abanerjee10 thanks for your question. This is method loads the gfa graph from file.
> 
> In the case of @gsc74 the assertion checks if a node line from the gfa file starts with "S ", so I suppose the graph he was using was starting with "Sx" (as for getting to the assertion the line needs to start with "S"). @gsc74 closed the issue back in the day, so this person probably knows better :)
> 
> In your case the assertion comes when parsing an edge line in the gfa file.
> 
> Thanks for providing the input for your issue, this is very helpful! I tried to reproduce your problem but I couldnt get the error, I used https://github.com/vgteam/vg/releases/tag/v1.46.0 to convert the vg file to gfa and got the following [graph](https://me.ariel.computer/files/BRCA1.gfa), which does not give me the assertion error. I wonder if this is related to the vg version. I also noted that in the last command you wrote `vg view BRCA1.vg >brca1.gaf` (instead of gfa, so maybe there was a small mistake related to that)

Hello @elarielcl and @abanerjee10, I believe the problem arose due to a typo error while creating the graph using `vg`. Instead of using `graph.vg`, I mistakenly used `graph.gfa`.

**Comment by abanerjee10** [comment]
Sorry, I put a typo in writing the command here, but the command I used was correct with >brca1.gfa instead of >brca1.gaf.

I was using vg version 1.43.0, and upgrading to vg version 1.46.0 resolved the issue.

Thanks!
